name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx
        continue-on-error: true

      - name: Build React App
        run: npm run build

      - name: Security Audit
        run: npm audit --audit-level=moderate
        continue-on-error: true

      - name: Lighthouse CI (Performance)
        run: |
          npm install -g @lhci/cli
          lhci autorun || echo "Lighthouse CI failed"
      - name: Run lint check
        run: npx eslint . --ext .js,.jsx || true



      - name: Expo Doctor Check (optional)
        run: npx expo-doctor
        continue-on-error: true
